scheme: "Poimandres"
author: "Oliver Cederborg"
base00: "1b1e28" # [colors.normal].black & [colors.cursor].text
base01: "717cb4" # [colors.selection].background & [colors.indexed_colors][19].color
base02: "272c3c" # [colors.selection].background
base03: "a6accd" # [colors.bright].black & [colors.primary].foreground
base04: "303340" # NOT USED
base05: "ffffff" # [colors.normal].white & [colors.bright].white
base06: "818ba3" # [colors.indexed_colors][20].color
base07: "0000ff" # NOT USED
base08: "d0679d" # [colors.normal].red & [colors.bright].red
base09: "cfd8e3" # [colors.indexed_colors][21].color
base0A: "fffac2" # [colors.normal].yellow & [colors.bright].yellow
base0B: "5de4c7" # [colors.normal].green & [colors.bright].green
base0C: "add7ff" # [colors.bright].cyan & [colors.bright].blue
base0D: "89ddff" # [colors.normal].blue & [colors.normal].cyan
base0E: "f087bd" # [colors.normal].magenta & [colors.bright].magenta
base0F: "f087bd" # NOT USED
