scheme: "Poimandres"
author: "Oliver Cederborg"
base00: "1b1e28" # Normal black or primary background
base01: "a6accd" # Bright black or less emphasized foreground
base02: "303340" # Selection background
base03: "525f78" # Midpoint between primary foreground and background for contrast (calculated placeholder)
base04: "818ba3" # Dark foreground (calculated placeholder)
base05: "a6accd" # Primary foreground
base06: "cfd8e3" # Light foreground (calculated placeholder)
base07: "ffffff" # White from the bright colors
base08: "d0679d" # Normal red
base09: "5de4c7" # Normal green
base0A: "fffac2" # Normal yellow
base0B: "89ddff" # Normal blue
base0C: "add7ff" # Normal cyan
base0D: "fcc5e9" # Normal magenta
base0E: "d0679d" # Bright red
base0F: "89ddff" # Bright cyan
