shell = "zsh -c '{}'"

# [[item]]
# file = "~/.config/nvim/colors/base16.vim"
# template = "vim"
# rewrite = true
# hook = "reloadnvim"

[[item]]
file = "~/.config/alacritty/alacritty.toml"
template = "alacritty"
subtemplate = "poimandres-256"

[[item]]
file = "~/.config/tmux/tmux.conf"
template = "tmux"
subtemplate = "default"
hook = "tmux source ~/.config/tmux/tmux.conf"
