apps:
  pages:
    - number: 1
    - number: 2
      items:
        - MacFamilyTree 9
        - Parallels Desktop
        - App Store
        - Mail
        - Contacts
        - Calendar
        - Reminders
        - Notes
        - FaceTime
        - Maps
        - Find My
        - Photo Booth
        - Photos
        - Preview
        - Music
        - Podcasts
        - TV
        - Voice Memos
        - Weather
        - News
        - Stocks
        - Books
        - Dictionary
        - Calculator
        - Freeform
        - folder: Browsers
          pages:
            - number: 1
              items:
                - Arc
                - Chromium
                - Firefox
                - Google Chrome
                - Microsoft Edge
                - Safari
    - number: 3
      items:
        - folder: Adobe
          pages:
            - number: 1
              items:
                - Adobe Creative Cloud
                - Adobe Lightroom
        - folder: Creative
          pages:
            - number: 1
              items:
                - Affinity Designer 2
                - Affinity Photo 2
                - Affinity Publisher 2
                - CameraBag Pro
                - Compressor
                - draw.io
                - Figma
                - Final Cut Pro
                - Link WIDE
                - Motion
                - TouchDesigner
        - folder: Media
          pages:
            - number: 1
              items:
                - Spotify
                - VLC
        - folder: Games
          pages:
            - number: 1
              items:
                - AetherSX2
                - Baldur's Gate 3
                - Celeste
                - Chess
                - Dolphin
                - Dolphin Updater
                - Hades
                - Hollow Knight
                - League of Legends
                - Melatonin
                - No Man's Sky
                - Origin
                - Riot Client
                - Shadow PC
                - Steam
                - FTL Faster Than Light
                - Papers, Please
        - folder: CrossOver
          pages:
            - number: 1
              items:
                - CrossOver
                - Risk of Rain Returns
                - Steam Support Center
        - folder: Development
          pages:
            - number: 1
              items:
                - Alacritty
                - Anaconda-Navigator
                - Developer
                - Docker
                - GitKraken
                - iTerm
                - Postman
                - PowerShell
                - Scriptable
                - Sublime Text
                - Steam
                - Visual Studio Code
                - Xcode
                - Apple Configurator
                - XrmToolBox
                - Web Server for Chrome
        - folder: Productivity
          pages:
            - number: 1
              items:
                - Anki
                - Todoist
        - folder: Writing
          pages:
            - number: 1
              items:
                - Notion
                - Obsidian
        - folder: OmniGroup
          pages:
            - number: 1
              items:
                - OmniGraffle
                - OmniPlan
        - folder: Reading
          pages:
            - number: 1
              items:
                - Ground News
                - Instapaper
                - Kindle
        - folder: Communication
          pages:
            - number: 1
              items:
                - Beeper
                - Discord
                - Messages
                - WhatsApp
                - zoom.us
        - folder: Safari Extensions
          pages:
            - number: 1
              items:
                - 1Password for Safari
                - Instapaper Save
                - OverPicture
                - Userscripts
        - folder: Sony
          pages:
            - number: 1
              items:
                - Edit
                - Imaging Edge Desktop
                - Remote
                - Viewer
        - Home
        - Clock
        - Siri
        - System Settings
        - Shortcuts
        - QuickTime Player
        - TextEdit
        - Time Machine
        - Font Book
        - Mission Control
        - Stickies
        - Image Capture
        - Automator
        - folder: Other
          pages:
            - number: 1
              items:
                - Grapher
                - VoiceOver Utility
                - AirPort Utility
                - Migration Assistant
                - Terminal
                - Activity Monitor
                - Console
                - Keychain Access
                - System Information
                - Script Editor
                - Disk Utility
                - Digital Colour Meter
                - ColorSync Utility
                - Screenshot
                - Bluetooth File Exchange
                - Audio MIDI Setup
                - Feedback Assistant
    - number: 4
      items:
        - Blender
        - folder: KiCad
          pages:
            - number: 1
              items:
                - KiCad
                - Bitmap2Component
                - Eeschema
                - GerbView
                - Page Layout Editor
                - PCB Calculator
                - Pcbnew
    - number: 5
      items:
        - folder: Utilities
          pages:
            - number: 1
              items:
                - 1Password
                - AlDente
                - Alfred 5
                - AltTab
                - Amethyst
                - Amphetamine
                - Bartender 4
                - Be Focused Pro
                - BetterSnapTool
                - Blackmagic Disk Speed Test
                - Dropbox
                - iStat Menus
                - Logi Options+
                - OBS
                - Screenflick
                - Surfshark
                - The Unarchiver
                - Velja
                - XLD
        - folder: Microsoft
          pages:
            - number: 1
              items:
                - Microsoft Excel
                - Microsoft OneNote
                - Microsoft Outlook
                - Microsoft PowerPoint
                - Microsoft Remote Desktop
                - Microsoft Teams (work or school)
                - Microsoft To Do
                - Microsoft Teams classic
                - Microsoft Word
                - OneDrive
    - number: 6
      items:
        - Ableton Live 11 Suite
        - Antelope Launcher
        - Audio Hijack
        - FM3-Edit
        - iLok License Manager
        - Logic Pro
        - Loopback
        - Max
        - Melodyne
        - Microtonic
        - MODALapp
        - MuseScore 3
        - Sonic Charge Authenticator
        - Spitfire Audio
        - Splice
        - SubLab
        - SubLabXL
        - Synplant
        - Vienna Ensemble Pro AU3
        - Vienna Ensemble Pro Server
        - folder: Native Instruments
          pages:
            - number: 1
              items:
                - Absynth 5
                - Battery 4
                - FM8
                - Guitar Rig 5
                - Kontakt
                - Kontakt 7
                - Massive
                - Native Access
                - Reaktor 6
        - folder: Steinberg
          pages:
            - number: 1
              items:
                - eLicenser Control Center
                - Groove Agent SE
                - HALion Sonic
                - SpectraLayers 9
                - Steinberg Activation Manager
                - Steinberg Download Assistant
                - Steinberg Library Manager
                - Nuendo 12
        - folder: Pioneer
          pages:
            - number: 1
              items:
                - Firmware Update Manager
                - INTERFACE2 Setting Utility
                - rekordbox
        - folder: Soundpaint
          pages:
            - number: 1
              items:
                - Soundpaint
                - Soundpaint Downloader
                - Soundpaint Editor
        - folder: QuNeo
          pages:
            - number: 1
              items:
                - QuNeo Editor
                - QuNeo MPE
                - QuNeome
        - folder: iZotope
          pages:
            - number: 1
              items:
                - iZotope Ozone 9
                - iZotope Product Portal
                - iZotope RX 7 Audio Editor
        - folder: Soundtoys
          pages:
            - number: 1
              items:
                - Remove Soundtoys
        - folder: Arturia
          pages:
            - number: 1
              items:
                - Analog Lab V
                - ARP 2600 V3
                - Arturia Software Center
                - Augmented STRINGS
                - Augmented VOICES
                - B-3 V2
                - Buchla Easel V
                - Clavinet V
                - CMI V
                - CS-80 V4
                - CZ V
                - DX7 V
                - Emulator II V
                - Farfisa V
                - Jun-6 V
                - Jup-8 V4
                - KORG MS-20 V
                - Matrix-12 V2
                - Mellotron V
                - Mini V3
                - Modular V3
                - OP-Xa V
                - Piano V3
                - Pigments
                - Prophet-5 V
                - Prophet-VS V
                - SEM V2
                - Solina V2
                - SQ80 V
                - Stage-73 V2
                - Synclavier V
                - Synthi V
                - Vocoder V
                - VOX Continental V2
                - Wurli V2
        - folder: Sugar Bytes
          pages:
            - number: 1
              items:
                - Cyclop
widgets:
  pages: []
dock_items:
  apps:
    - /Applications/Arc.app
    - /Applications/Beeper.app
    - /Applications/Spotify.app
    - /Applications/Visual Studio Code.app
    - /Applications/Alacritty.app
    - /Applications/Todoist.app
    - /Applications/Obsidian.app
  settings:
    autohide: true
    largesize: 128
    magnification: false
    minimize-to-application: false
    mru-spaces: false
    show-recents: false
    tilesize: 57
desktop: {}
