apps:
  pages:
    - number: 1
      items:
        - Contacts
        - Calendar
        - Home
        - Clock
        - System Settings
        - folder: MacOS
          pages:
            - number: 1
              items:
                - App Store
                - Books
                - Calculator
                - Dictionary
                - Find My
                - Freeform
                - Maps
                - News
                - Notes
                - Photo Booth
                - Photos
                - Podcasts
                - Preview
                - Reminders
                - Siri
                - Stocks
                - Voice Memos
                - Weather
        - folder: MacOS (Other)
          pages:
            - number: 1
              items:
                - Activity Monitor
                - AirPort Utility
                - Audio MIDI Setup
                - Automator
                - Bluetooth File Exchange
                - ColorSync Utility
                - Console
                - Digital Colour Meter
                - Disk Utility
                - Feedback Assistant
                - Font Book
                - Grapher
                - Image Capture
                - Keychain Access
                - Migration Assistant
                - Mission Control
                - QuickTime Player
                - Screenshot
                - Script Editor
                - Stickies
                - System Information
                - Terminal
                - TextEdit
                - Time Machine
                - VoiceOver Utility
        - folder: Communication
          pages:
            - number: 1
              items:
                - Beeper
                - Discord
                - FaceTime
                - Mail
                - Messages
                - WhatsApp
                - zoom.us
        - folder: Media
          pages:
            - number: 1
              items:
                - Music
                - Spotify
                - TV
                - VLC
        - folder: Developer
          pages:
            - number: 1
              items:
                - Alacritty
                - Anaconda-Navigator
                - Apple Configurator
                - Developer
                - Docker
                - GitKraken
                - iTerm
                - Postman
                - PowerShell
                - Scriptable
                - Shortcuts
                - Sublime Text
                - Visual Studio Code
                - Web Server for Chrome
                - Xcode
                - XrmToolBox
        - folder: Creative
          pages:
            - number: 1
              items:
                - Affinity Designer 2
                - Affinity Photo 2
                - Affinity Publisher 2
                - CameraBag Pro
                - Compressor
                - draw.io
                - Figma
                - Final Cut Pro
                - Link WIDE
                - Motion
                - TouchDesigner
        - folder: Games
          pages:
            - number: 1
              items:
                - AetherSX2
                - Baldur's Gate 3
                - Celeste
                - Chess
                - Dolphin
                - Dolphin Updater
                - FTL Faster Than Light
                - Hades
                - Hollow Knight
                - League of Legends
                - Melatonin
                - No Man's Sky
                - Origin
                - Papers, Please
                - Riot Client
                - Shadow PC
                - Steam
        - folder: CrossOver
          pages:
            - number: 1
              items:
                - CrossOver
                - Risk of Rain Returns
                - Steam
                - Steam Support Center
        - folder: Productivity
          pages:
            - number: 1
              items:
                - Anki
                - Ground News
                - Instapaper
                - Kindle
                - Notion
                - Obsidian
                - OmniGraffle
                - OmniPlan
                - Parallels Desktop
                - Todoist
        - folder: Utilities
          pages:
            - number: 1
              items:
                - 1Password
                - AlDente
                - Alfred 5
                - AltTab
                - Amethyst
                - Amphetamine
                - Bartender 4
                - Be Focused Pro
                - BetterSnapTool
                - Blackmagic Disk Speed Test
                - Dropbox
                - iStat Menus
                - Logi Options+
                - OBS
                - Screenflick
                - Surfshark
                - The Unarchiver
                - Velja
                - XLD
        - folder: Microsoft
          pages:
            - number: 1
              items:
                - Microsoft Excel
                - Microsoft OneNote
                - Microsoft Outlook
                - Microsoft PowerPoint
                - Microsoft Remote Desktop
                - Microsoft Teams (work or school)
                - Microsoft Teams classic
                - Microsoft To Do
                - Microsoft Word
                - OneDrive
        - MacFamilyTree 9
        - folder: Browsers
          pages:
            - number: 1
              items:
                - Arc
                - Chromium
                - Firefox
                - Google Chrome
                - Microsoft Edge
                - Safari
    - number: 2
      items:
        - Blender
        - folder: KiCad
          pages:
            - number: 1
              items:
                - Bitmap2Component
                - Eeschema
                - GerbView
                - KiCad
                - Page Layout Editor
                - PCB Calculator
                - Pcbnew
        - folder: Adobe
          pages:
            - number: 1
              items:
                - Adobe Creative Cloud
                - Adobe Lightroom
        - folder: Sony
          pages:
            - number: 1
              items:
                - Edit
                - Imaging Edge Desktop
                - Remote
                - Viewer
        - folder: Safari Extensions
          pages:
            - number: 1
              items:
                - 1Password for Safari
                - Instapaper Save
                - OverPicture
                - Userscripts
    - number: 3
      items:
        - Ableton Live 11 Suite
        - Logic Pro
        - Max
        - MuseScore 3
        - Nuendo 12
        - rekordbox
        - folder: Audio (Utilities)
          pages:
            - number: 1
              items:
                - Audio Hijack
                - Loopback
                - Splice
        - folder: Audio (Launchers)
          pages:
            - number: 1
              items:
                - Antelope Launcher
                - FM3-Edit
        - folder: Audio (Authorisation)
          pages:
            - number: 1
              items:
                - Arturia Software Center
                - iLok License Manager
                - iZotope Product Portal
                - Native Access
                - Sonic Charge Authenticator
                - Spitfire Audio
        - folder: Audio (Plugins)
          pages:
            - number: 1
              items:
                - Cyclop
                - iZotope Ozone 9
                - iZotope RX 7 Audio Editor
                - Melodyne
                - Microtonic
                - MODALapp
                - SubLab
                - SubLabXL
                - Synplant
        - folder: Arturia
          pages:
            - number: 1
              items:
                - Analog Lab V
                - ARP 2600 V3
                - Augmented STRINGS
                - Augmented VOICES
                - B-3 V2
                - Buchla Easel V
                - Clavinet V
                - CMI V
                - CS-80 V4
                - CZ V
                - DX7 V
                - Emulator II V
                - Farfisa V
                - Jun-6 V
                - Jup-8 V4
                - KORG MS-20 V
                - Matrix-12 V2
                - Mellotron V
                - Mini V3
                - Modular V3
                - OP-Xa V
                - Piano V3
                - Pigments
                - Prophet-5 V
            - number: 2
              items:
                - Prophet-VS V
                - SEM V2
                - Solina V2
                - SQ80 V
                - Stage-73 V2
                - Synclavier V
                - Synthi V
                - Vocoder V
                - VOX Continental V2
                - Wurli V2
        - folder: Native Instruments
          pages:
            - number: 1
              items:
                - Absynth 5
                - Battery 4
                - FM8
                - Guitar Rig 5
                - Kontakt
                - Kontakt 7
                - Massive
                - Reaktor 6
        - folder: Pioneer
          pages:
            - number: 1
              items:
                - Firmware Update Manager
                - INTERFACE2 Setting Utility
        - folder: QuNeo
          pages:
            - number: 1
              items:
                - QuNeo Editor
                - QuNeo MPE
                - QuNeome
        - folder: Soundpaint
          pages:
            - number: 1
              items:
                - Soundpaint
                - Soundpaint Downloader
                - Soundpaint Editor
        - folder: Soundtoys
          pages:
            - number: 1
              items:
                - Remove Soundtoys
        - folder: Steinberg
          pages:
            - number: 1
              items:
                - eLicenser Control Center
                - Groove Agent SE
                - HALion Sonic
                - SpectraLayers 9
                - Steinberg Activation Manager
                - Steinberg Download Assistant
                - Steinberg Library Manager
        - folder: Vienna Ensemble
          pages:
            - number: 1
              items:
                - Vienna Ensemble Pro AU3
                - Vienna Ensemble Pro Server
widgets:
  pages: []
dock_items:
  apps:
    - /Applications/Arc.app
    - /Applications/Beeper.app
    - /Applications/Spotify.app
    - /Applications/Visual Studio Code.app
    - /Applications/Alacritty.app
    - /Applications/Todoist.app
    - /Applications/Obsidian.app
  settings:
    autohide: true
    largesize: 128
    magnification: false
    minimize-to-application: false
    mru-spaces: false
    show-recents: false
    tilesize: 57
desktop: {}
