# https://alacritty.org/config-alacritty.html

live_config_reload = true

[[colors.indexed_colors]]
color = "0xf8bd96"
index = 16

[[colors.indexed_colors]]
color = "0xf38ba8"
index = 17

[[colors.indexed_colors]]
color = "0x282737"
index = 18

[[colors.indexed_colors]]
color = "0x2f2e3e"
index = 19

[[colors.indexed_colors]]
color = "0x414050"
index = 20

[[colors.indexed_colors]]
color = "0xccd3e1"
index = 21

[colors.bright]
black = "0x383747"
blue = "0x89b4fa"
cyan = "0x89dceb"
green = "0xabe9b3"
magenta = "0xcba6f7"
red = "0xf38ba8"
white = "0xd9e0ee"
yellow = "0xfae3b0"

[colors.cursor]
cursor = "0xbfc6d4"
text = "0x1e1d2d"

[colors.normal]
black = "0x1e1d2d"
blue = "0x89b4fa"
cyan = "0x89dceb"
green = "0xabe9b3"
magenta = "0xcba6f7"
red = "0xf38ba8"
white = "0xbfc6d4"
yellow = "0xfae3b0"

[colors.primary]
background = "0x1e1d2d"
foreground = "0xbfc6d4"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 16.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# https://alacritty.org/config-alacritty-bindings.html

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
post_processing = true
persist = false
action = "Select"                                                                                                                                         # "Copy" | "Paste" | "Select" | "MoveViModeCursor"
command = { program = "open", args = [] }
binding = { key = "U", mods = "Control|Shift" }
mouse = { mods = "Command", enabled = true }

[scrolling]
history = 100000
multiplier = 1

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[terminal]
osc52 = "CopyPaste" # "Disabled" | "OnlyCopy" | "OnlyPaste" | "CopyPaste"

[window]
decorations = "Buttonless" # "Full" | "None" | "Transparent" | "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.75
blur = true                # true | false # (works on macOS/KDE Wayland)
title = "Alacritty"
startup_mode = "Windowed"  # "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
