# https://alacritty.org/config-alacritty.html

live_config_reload = true

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
post_processing = true
persist = false
# action: "Copy" | "Paste" | "Select" | "MoveViModeCursor"
action = "Select"
command = { program = "open", args = [] }
binding = { key = "U", mods = "Control|Shift" }
mouse = { mods = "Command", enabled = true }

[scrolling]
history = 100000
multiplier = 1

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[terminal]
# osc52: "Disabled" | "OnlyCopy" | "OnlyPaste" | "CopyPaste"
osc52 = "CopyPaste"

[window]
# decorations: "Full" | "None" | "Transparent" | "Buttonless"
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.75
# blur: true | false # (works on macOS/KDE Wayland)
blur = true
title = "Alacritty"
# startup_mode: "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Windowed"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 16.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# https://alacritty.org/config-alacritty-bindings.html

[[keyboard.bindings]]
key = "c"
mods = "Control"
chars = "\u001Bc"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001Bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001Bf"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0001"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0005"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\u001B\u007F"

# Start flavours
# Base16 Catppuccin 256 - alacritty color config
# https://github.com/NvChad/base46

# Default colors
[colors.primary]
background = '0x1e1d2d'
foreground = '0xbfc6d4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1e1d2d'
cursor = '0xbfc6d4'

# Normal colors
[colors.normal]
black = '0x1e1d2d'
red = '0xf38ba8'
green = '0xabe9b3'
yellow = '0xfae3b0'
blue = '0x89b4fa'
magenta = '0xcba6f7'
cyan = '0x89dceb'
white = '0xbfc6d4'

# Bright colors
[colors.bright]
black = '0x383747'
red = '0xf38ba8'
green = '0xabe9b3'
yellow = '0xfae3b0'
blue = '0x89b4fa'
magenta = '0xcba6f7'
cyan = '0x89dceb'
white = '0xd9e0ee'

[[colors.indexed_colors]]
index = 16
color = "0xf8bd96"

[[colors.indexed_colors]]
index = 17
color = "0xf38ba8"

[[colors.indexed_colors]]
index = 18
color = "0x282737"

[[colors.indexed_colors]]
index = 19
color = "0x2f2e3e"

[[colors.indexed_colors]]
index = 20
color = "0x414050"

[[colors.indexed_colors]]
index = 21
color = "0xccd3e1"
# End flavours
