# https://alacritty.org/config-alacritty.html

live_config_reload = true

[scrolling]
history = 100000
multiplier = 1

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[terminal]
# osc52: "Disabled" | "OnlyCopy" | "OnlyPaste" | "CopyPaste"
osc52 = "CopyPaste"

[window]
# decorations: "Full" | "None" | "Transparent" | "Buttonless"
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.90
# blur: true | false # (works on macOS/KDE Wayland)
blur = true
title = "Alacritty"
# startup_mode: "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Windowed"
option_as_alt = "Both"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 5

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 16.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# https://alacritty.org/config-alacritty-bindings.html

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001Bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001Bf"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0001"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0005"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\u001B\u007F"

[colors]
draw_bold_text_with_bright_colors = true

# Start flavours
# Base16 Poimandres 256 - alacritty color config
# Oliver Cederborg

# Default colors
[colors.primary]
background = '#1b1e28'
foreground = '#a6accd'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#1b1e28'
cursor = '#a6accd'

# Normal colors
[colors.normal]
black = '#1b1e28'
red = '#d0679d'
green = '#5de4c7'
yellow = '#fffac2'
blue = '#89ddff'
magenta = '#f087bd'
cyan = '#89ddff'
white = '#ffffff'

# Bright colors
[colors.bright]
black = '#a6accd'
red = '#d0679d'
green = '#5de4c7'
yellow = '#fffac2'
blue = '#add7ff'
magenta = '#f087bd'
cyan = '#add7ff'
white = '#ffffff'

[[colors.indexed_colors]]
index = 16
color = "#5de4c7"

[[colors.indexed_colors]]
index = 17
color = "#89ddff"

[[colors.indexed_colors]]
index = 18
color = "#a6accd"

[[colors.indexed_colors]]
index = 19
color = "#303340"

[[colors.indexed_colors]]
index = 20
color = "#818ba3"

[[colors.indexed_colors]]
index = 21
color = "#cfd8e3"

[colors.selection]
text = "CellForeground"
background = "#272c3c"
# End flavours
